// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3hp5wTvoQfpfX-LDqV0e17JIgX8hjX1M',
    appId: '1:1033270227566:web:66c86b761e666709592c7f',
    messagingSenderId: '1033270227566',
    projectId: 'chati-f6518',
    authDomain: 'chati-f6518.firebaseapp.com',
    storageBucket: 'chati-f6518.firebasestorage.app',
    measurementId: 'G-40NGX6EJYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAts0zM0gQ0stlS9t-RQq8RXMNBtJVWNnw',
    appId: '1:1033270227566:android:a049db73dc9ec448592c7f',
    messagingSenderId: '1033270227566',
    projectId: 'chati-f6518',
    storageBucket: 'chati-f6518.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTVQL_dj4-aEXbrcsUeHz8meiTEV6iULE',
    appId: '1:1033270227566:ios:c30de2d07c0bab28592c7f',
    messagingSenderId: '1033270227566',
    projectId: 'chati-f6518',
    storageBucket: 'chati-f6518.firebasestorage.app',
    iosBundleId: 'com.example.chati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTVQL_dj4-aEXbrcsUeHz8meiTEV6iULE',
    appId: '1:1033270227566:ios:c30de2d07c0bab28592c7f',
    messagingSenderId: '1033270227566',
    projectId: 'chati-f6518',
    storageBucket: 'chati-f6518.firebasestorage.app',
    iosBundleId: 'com.example.chati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3hp5wTvoQfpfX-LDqV0e17JIgX8hjX1M',
    appId: '1:1033270227566:web:3ec9a7dbc6b32cf5592c7f',
    messagingSenderId: '1033270227566',
    projectId: 'chati-f6518',
    authDomain: 'chati-f6518.firebaseapp.com',
    storageBucket: 'chati-f6518.firebasestorage.app',
    measurementId: 'G-JMW5518J7N',
  );
}
